### PR TITLE
Switching to scikit-build

### PR DESCRIPTION
**Pull request by tdegeus**

### CODE REVIEW

**Comment by tdegeus** [comment]
@henryiii Thanks for *scikit-build*! It will simplify a lot of maintenance. 

I'm trying to use it to see if I can work around my ARM OSx issues. However, it seems that I'm still making a user error, because *scikit-build* fails to install my shared-object. I could not find any more hints in the manual. Do you see what I'm doing wrong ?

**Comment by henryiii** [comment]
I can try to help later, but for now, https://github.com/scikit-build/scikit-build-sample-projects/pull/8 (that repo as well as that PR) might have some good ideas.

**Comment by tdegeus** [comment]
Thanks @henryiii . It seems that there is always a `*.py` needed, can't that be avoided ? The shared-object contains everything

**Comment by henryiii** [comment]
Sticking it in a package folder is likely a good idea - if you want to add a `.pyi` file someday, for example, it's a lot nicer if it's already a folder, rather than spamming the site-packages. Also, you often have a bit of setup eventually that is easier placed in a .py file. But maybe that should be supported.

**Comment by tdegeus** [comment]
See https://github.com/conda-forge/qpot-feedstock/pull/31 and https://github.com/conda-forge/qpot-feedstock/pull/32 for conda build ideas

**Pull request merged**
